### ISSUE TITLE
Test Issues Mail Notifications

### ISSUE THREAD

**Issue by Touille** [Touille/Singularity-Keys-Press-Addon#1]
**TEST**

**Comment by mendocinotim** [comment]
I got it.

--Timothy Hall
mendocinotim@gmail.com
(707) 357-6807

**Comment by mendocinotim** [comment]
Touille,

I thought I would take a moment and try to figure out a little about creating a wiki on GitHub.
Although markup works, the formatting options are more limited than HTML.
And I am reading that these Wikis will also accept HTML.

Scrivener has an HTML export option.
This is what the output files look like..



How would I bring this into the Wiki?


--Timothy Hall
mendocinotim@gmail.com
(707) 357-6807
